volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: spatorna66/kittygram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: spatorna66/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/static
  gateway:
    image: spatorna66/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/
    ports:
      - 9000:80

